# https://taskfile.dev
version: "3"

tasks:
  release:
    desc: Tag and upload release
    cmds:
      - which gh
      - test v{{.CLI_ARGS}}
      - git tag v{{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes v{{.CLI_ARGS}}

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  test:
    desc: Run go tests with coverage and timeout and without cache
    cmds:
      - go test -count 1 -cover -timeout 1s ./...

  all:
    desc: Run all tests and linters
    cmds:
      - task: lint
      - task: test
